# Generated by Django 3.2.3 on 2021-05-30 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_comment', to='courses_app.course')),
                ('rating', models.ForeignKey(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐⭐')], default=1, max_length=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_rating', to='courses_app.course')),
            ],
        ),
    ]
