# Generated by Django 3.2.3 on 2021-05-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_auto_20210530_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='comment',
        ),
    ]
